#pragma config(Sensor, S3,     color,          sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     proximity,      sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          arm,           tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          wheelLeft,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          wheelRight,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void checkRoom();
void straight(int n);
void reverse(int n);
void turnleft();
void turnright();

void wallRoom();
void fireRoom();
void emptyRoom();

//Tracker variables
int clearRoom = 0;
int fireRoom = 0;
int walledRoom = 0;
int helpTheLegoMan = 0;

task main()
{
	checkRoom();
}

void checkRoom()
{
	//Check if clockwise or anticlockwise
	turnleft();
	wait1Msec(1000);


	if(SensorValue(S4) < 10)
	{
		turnright();
		wait1Msec(1000);
		straight(10);
		//Check for walledRoom
		if(SensorValue(S4) < 10)
		{
			walledRoom = 1;
			wallRoom();
			break;
		}

		//Check for fireRoom
		while(SensorValue(S4) > 10 && SensorValue(S3) != 5 && fireRoom == 0)
		{
			straight(1);
			if(SensorValue(S3) == 5)
			{
				fireRoom();
				fireRoom = 1;
				break;
			}
		}
	}
	else
	{
		turnleft();
		fireRoom();
	}
}

void fireRoom()
{
	while(SensorValue(S3) != 5)
	{
		straight(1);
	}
	turnright();
	turnright();
	reverse(700);
	turnright();
	if(SensorValue(S4 < 5)
	{
		straight(2000);
	}
	else
	{
		turnleft();
		turnleft();
		straight(2000);
	}
}

void wallRoom()
{
		straight(700);
		turnright();
		straight(900);
		turnleft();
		straight(1100);
}

void emptyRoom()
{
	turnright();
	straight(1500);
	turnright();
	//checkSoundFile("Analyze");
	straight(1700);
}

void straight(int n)
{
	motor[motorB] = 50;
	motor[motorC] = 50;
	wait1Msec(n);
}

void turnleft()
{
	motor[motorB] = -10	;
	motor[motorC] = 35;
	wait1Msec(800);
	motor[motorB] = 0;
	motor[motorC] = 0;
}

void turnright()
{
	motor[motorB] = 30;
	motor[motorC] = -15;
	wait1Msec(800);
	motor[motorB] = 0;
	motor[motorC] = 0;
}

void reverse(int n)
{
	motor[motorB] = -50;
	motor[motorC] = -50;
	wait1Msec(n);
}
